function [featureTable,outputTable] = feature_gen_t2_1st(inputData)
%DIAGNOSTICFEATURES recreates results in Diagnostic Feature Designer.
%
% Input:
%  inputData: A table or a cell array of tables/matrices containing the
%  data as those imported into the app.
%
% Output:
%  featureTable: A table containing all features and condition variables.
%  outputTable: A table containing the computation results.
%
% This function computes features:
%  Case_sigstats/Mean
%  Case_sigstats/RMS
%  Case_sigstats_1/ClearanceFactor
%  Case_sigstats_1/CrestFactor
%  Case_sigstats_1/ImpulseFactor
%  Case_sigstats_1/Mean
%  Case_sigstats_1/PeakValue
%  Case_sigstats_1/ShapeFactor
%  Case_sigstats_1/Std
%  Case_sigstats_2/Mean
%  Case_sigstats_2/PeakValue
%  Case_sigstats_2/RMS
%  Case_sigstats_2/Std
%  Case_sigstats_3/Std
%  Case_sigstats_5/ClearanceFactor
%  Case_sigstats_5/Mean
%  Case_sigstats_5/RMS
%  Case_sigstats_5/Std
%
% Frame Policy:
%  Frame name: FRM_1
%  Frame size: 0.128 seconds
%  Frame rate: 0.128 seconds
%
% Organization of the function:
% 1. Compute signals/spectra/features
% 2. Extract computed features into a table
%
% Modify the function to add or remove data processing, feature generation
% or ranking operations.

% Auto-generated by MATLAB on 17-Feb-2025 12:35:56

% Create output ensemble.
outputEnsemble = workspaceEnsemble(inputData,'DataVariables',"Case",'ConditionVariables',"Task2");

% Reset the ensemble to read from the beginning of the ensemble.
reset(outputEnsemble);

% Append new frame policy name to DataVariables.
outputEnsemble.DataVariables = [outputEnsemble.DataVariables;"FRM_1"];

% Set SelectedVariables to select variables to read from the ensemble.
outputEnsemble.SelectedVariables = "Case";

% Initialize a cell array to store all the results.
allMembersResult = {};

% Loop through all ensemble members to read and write data.
while hasdata(outputEnsemble)
    % Read one member.
    member = read(outputEnsemble);

    % Read signals.
    Case_full = readMemberData(member,"Case",["TIME","P7","P1","P2","P3","P5"]);

    % Get the frame intervals.
    lowerBound = Case_full.TIME(1);
    upperBound = Case_full.TIME(end);
    fullIntervals = frameintervals([lowerBound upperBound],0.128,0.128,'FrameUnit',"seconds");
    intervals = fullIntervals;

    % Initialize a table to store frame results.
    frames = table;

    % Loop through all frame intervals and compute results.
    for ct = 1:height(intervals)
        % Get all input variables.
        Case = Case_full(Case_full.TIME>=intervals{ct,1}&Case_full.TIME<intervals{ct,2},:);

        % Initialize a table to store results for one frame interval.
        frame = intervals(ct,:);

        %% SignalFeatures
        try
            % Compute signal features.
            inputSignal = Case.P7;
            Mean = mean(inputSignal,'omitnan');
            RMS = rms(inputSignal,'omitnan');

            % Concatenate signal features.
            featureValues = [Mean,RMS];

            % Store computed features in a table.
            featureNames = {'Mean','RMS'};
            Case_sigstats = array2table(featureValues,'VariableNames',featureNames);
        catch
            % Store computed features in a table.
            featureValues = NaN(1,2);
            featureNames = {'Mean','RMS'};
            Case_sigstats = array2table(featureValues,'VariableNames',featureNames);
        end

        % Append computed results to the frame table.
        frame = [frame, ...
            table({Case_sigstats},'VariableNames',{'Case_sigstats'})];

        %% SignalFeatures
        try
            % Compute signal features.
            inputSignal = Case.P1;
            ClearanceFactor = max(abs(inputSignal))/(mean(sqrt(abs(inputSignal)))^2);
            CrestFactor = peak2rms(inputSignal);
            ImpulseFactor = max(abs(inputSignal))/mean(abs(inputSignal));
            Mean = mean(inputSignal,'omitnan');
            PeakValue = max(abs(inputSignal));
            ShapeFactor = rms(inputSignal,'omitnan')/mean(abs(inputSignal),'omitnan');
            Std = std(inputSignal,'omitnan');

            % Concatenate signal features.
            featureValues = [ClearanceFactor,CrestFactor,ImpulseFactor,Mean,PeakValue,ShapeFactor,Std];

            % Store computed features in a table.
            featureNames = {'ClearanceFactor','CrestFactor','ImpulseFactor','Mean','PeakValue','ShapeFactor','Std'};
            Case_sigstats_1 = array2table(featureValues,'VariableNames',featureNames);
        catch
            % Store computed features in a table.
            featureValues = NaN(1,7);
            featureNames = {'ClearanceFactor','CrestFactor','ImpulseFactor','Mean','PeakValue','ShapeFactor','Std'};
            Case_sigstats_1 = array2table(featureValues,'VariableNames',featureNames);
        end

        % Append computed results to the frame table.
        frame = [frame, ...
            table({Case_sigstats_1},'VariableNames',{'Case_sigstats_1'})];

        %% SignalFeatures
        try
            % Compute signal features.
            inputSignal = Case.P2;
            Mean = mean(inputSignal,'omitnan');
            PeakValue = max(abs(inputSignal));
            RMS = rms(inputSignal,'omitnan');
            Std = std(inputSignal,'omitnan');

            % Concatenate signal features.
            featureValues = [Mean,PeakValue,RMS,Std];

            % Store computed features in a table.
            featureNames = {'Mean','PeakValue','RMS','Std'};
            Case_sigstats_2 = array2table(featureValues,'VariableNames',featureNames);
        catch
            % Store computed features in a table.
            featureValues = NaN(1,4);
            featureNames = {'Mean','PeakValue','RMS','Std'};
            Case_sigstats_2 = array2table(featureValues,'VariableNames',featureNames);
        end

        % Append computed results to the frame table.
        frame = [frame, ...
            table({Case_sigstats_2},'VariableNames',{'Case_sigstats_2'})];

        %% SignalFeatures
        try
            % Compute signal features.
            inputSignal = Case.P3;
            Std = std(inputSignal,'omitnan');

            % Concatenate signal features.
            featureValues = Std;

            % Store computed features in a table.
            featureNames = {'Std'};
            Case_sigstats_3 = array2table(featureValues,'VariableNames',featureNames);
        catch
            % Store computed features in a table.
            featureValues = NaN(1,1);
            featureNames = {'Std'};
            Case_sigstats_3 = array2table(featureValues,'VariableNames',featureNames);
        end

        % Append computed results to the frame table.
        frame = [frame, ...
            table({Case_sigstats_3},'VariableNames',{'Case_sigstats_3'})];

        %% SignalFeatures
        try
            % Compute signal features.
            inputSignal = Case.P5;
            ClearanceFactor = max(abs(inputSignal))/(mean(sqrt(abs(inputSignal)))^2);
            Mean = mean(inputSignal,'omitnan');
            RMS = rms(inputSignal,'omitnan');
            Std = std(inputSignal,'omitnan');

            % Concatenate signal features.
            featureValues = [ClearanceFactor,Mean,RMS,Std];

            % Store computed features in a table.
            featureNames = {'ClearanceFactor','Mean','RMS','Std'};
            Case_sigstats_5 = array2table(featureValues,'VariableNames',featureNames);
        catch
            % Store computed features in a table.
            featureValues = NaN(1,4);
            featureNames = {'ClearanceFactor','Mean','RMS','Std'};
            Case_sigstats_5 = array2table(featureValues,'VariableNames',featureNames);
        end

        % Append computed results to the frame table.
        frame = [frame, ...
            table({Case_sigstats_5},'VariableNames',{'Case_sigstats_5'})];

        %% Concatenate frames.
        frames = [frames;frame]; %#ok<*AGROW>
    end
    % Append all member results to the cell array.
    memberResult = table({frames},'VariableNames',"FRM_1");
    allMembersResult = [allMembersResult; {memberResult}]; %#ok<AGROW>
end

% Write the results for all members to the ensemble.
writeToMembers(outputEnsemble,allMembersResult)

% Gather all features into a table.
selectedFeatureNames = ["FRM_1/Case_sigstats/Mean","FRM_1/Case_sigstats/RMS","FRM_1/Case_sigstats_1/ClearanceFactor","FRM_1/Case_sigstats_1/CrestFactor","FRM_1/Case_sigstats_1/ImpulseFactor","FRM_1/Case_sigstats_1/Mean","FRM_1/Case_sigstats_1/PeakValue","FRM_1/Case_sigstats_1/ShapeFactor","FRM_1/Case_sigstats_1/Std","FRM_1/Case_sigstats_2/Mean","FRM_1/Case_sigstats_2/PeakValue","FRM_1/Case_sigstats_2/RMS","FRM_1/Case_sigstats_2/Std","FRM_1/Case_sigstats_3/Std","FRM_1/Case_sigstats_5/ClearanceFactor","FRM_1/Case_sigstats_5/Mean","FRM_1/Case_sigstats_5/RMS","FRM_1/Case_sigstats_5/Std"];
featureTable = readFeatureTable(outputEnsemble,"FRM_1",'Features',selectedFeatureNames,'ConditionVariables',outputEnsemble.ConditionVariables,'IncludeMemberID',true);

% Set SelectedVariables to select variables to read from the ensemble.
outputEnsemble.SelectedVariables = unique([outputEnsemble.DataVariables;outputEnsemble.ConditionVariables;outputEnsemble.IndependentVariables],'stable');

% Gather results into a table.
if nargout > 1
    outputTable = readall(outputEnsemble);
end
end
